[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "nss", "freetype", "freetype-dev", "harfbuzz", "ca-certificates", "ttf-freefont", "font-noto-emoji"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node server.js"
