[phases.setup]
nixPkgs = ["nodejs_20", "chromium", "nss", "freetype", "harfbuzz", "cacert", "liberation_ttf", "noto-fonts-emoji"]

[phases.install]
cmds = ["npm install"]

[start]
cmd = "node server.js"
